```{r echo=FALSE,message=FALSE,results="asis"}
var.name = gsub("_"," ",var)
cat(paste("\n\n### Side effect: ",stringr::str_to_title(var.name),"\n"))
data_caption = paste0("Change in", var.name ,"ratings from pre to post first drug administration. Each line represents an individual. The drug effect is reflected in the slope of the lines.")
results_caption = paste0("Posterior distributions of estimated drug effects on self-reported",var.name," on a 0-100 VAS within and across men and women, as well as the difference between sexes (women-men). Density plots show posterior distributions. Dots and lines indicate means, and 50 & 95% credible intervals.")
```

```{r, echo=show.details, message=FALSE,results="asis", fig.cap=data_caption, fig.height=2.5}
the_data = 
  make_the_data(
    select_data(c(var)) %>% .[stage %in% 4:5],
    phase = "drug") %>% 
  .[, outcome := var]

the_data = 
  the_data %>%
  .[, Drug := factor(Drug, levels = c("placebo","oxycodone"))] %>% 
  coarsen(var = "response", bins = 20, range = c(0,100))
the_data %>% plot_pre_post("drug") + scale_color_manual(values = c("black","blue"))
```

```{r, echo=show.details, message=FALSE,results="asis"}
fn = paste0("fits/",var,"_acat.Rdata")
if (file.exists(fn)) {
    load(fn)
  } else {
    fit = fit_ordinal_model(the_data, drug_formula, fn, family = acat())
  }
```

```{r}
cat(paste0(length(unique(fit$data$participant)), " participants were included in this analysis."))
```

```{r, echo=show.details, message=FALSE,results="asis", , fig.cap=results_caption, fig.height=2.5}
tmp = plot_prepost_contrast(fit, the_data, var , my_contrast = "drug")
tmp$plot+ggtitle(paste0("Oxycodone effect on '", gsub("_"," ",var), "' rating"))+xlab("Oxycodone effect: oxycodone (post - pre) - placebo (post - pre)")
```

```{r, echo=FALSE,results="asis"}
tmp$table
```

```{r, echo = FALSE, results='asis'}
write_drug_effect(tmp[[2]],var.name)
```

